import { EFan } from 'common/types/mahjong';

export const IMPLIED_FANS: Partial<Record<EFan, EFan[]>> = {
  // 88 points
  [EFan.BIG_FOUR_WINDS]: [
    EFan.BIG_THREE_WINDS,
    EFan.ALL_PUNGS,
    EFan.SEAT_WIND,
    EFan.PREVALENT_WIND,
    EFan.PUNG_OF_TERMINALS_OR_HONORS,
  ],
  [EFan.BIG_THREE_DRAGONS]: [EFan.TWO_DRAGON_PUNGS, EFan.DRAGON_PUNG, EFan.PUNG_OF_TERMINALS_OR_HONORS],
  [EFan.NINE_GATES]: [EFan.FULL_FLUSH, EFan.CONCEALED_HAND, EFan.PUNG_OF_TERMINALS_OR_HONORS, EFan.NO_HONORS],
  [EFan.FOUR_KONGS]: [
    EFan.THREE_KONGS,
    EFan.TWO_CONCEALED_KONGS,
    EFan.TWO_MELDED_KONGS,
    EFan.CONCEALED_KONG,
    EFan.MELDED_KONG,
    EFan.ALL_PUNGS,
    EFan.SINGLE_WAIT,
  ],
  [EFan.SEVEN_SHIFTED_PAIRS]: [
    EFan.SEVEN_PAIRS,
    EFan.FULL_FLUSH,
    EFan.CONCEALED_HAND,
    EFan.SINGLE_WAIT,
    EFan.NO_HONORS,
  ],
  [EFan.THIRTEEN_ORPHANS]: [EFan.ALL_TYPES, EFan.ALL_TERMINALS_AND_HONORS, EFan.CONCEALED_HAND, EFan.SINGLE_WAIT],

  // 64 points
  [EFan.ALL_TERMINALS]: [
    EFan.ALL_TERMINALS_AND_HONORS,
    EFan.ALL_PUNGS,
    EFan.OUTSIDE_HAND,
    EFan.PUNG_OF_TERMINALS_OR_HONORS,
    EFan.NO_HONORS,
  ],
  [EFan.LITTLE_FOUR_WINDS]: [EFan.BIG_THREE_WINDS, EFan.PUNG_OF_TERMINALS_OR_HONORS],
  [EFan.LITTLE_THREE_DRAGONS]: [EFan.TWO_DRAGON_PUNGS, EFan.DRAGON_PUNG, EFan.PUNG_OF_TERMINALS_OR_HONORS],
  [EFan.ALL_HONORS]: [
    EFan.ALL_TERMINALS_AND_HONORS,
    EFan.ALL_PUNGS,
    EFan.PUNG_OF_TERMINALS_OR_HONORS,
    EFan.OUTSIDE_HAND,
  ],
  [EFan.FOUR_CONCEALED_PUNGS]: [
    EFan.ALL_PUNGS,
    EFan.THREE_CONCEALED_PUNGS,
    EFan.TWO_CONCEALED_PUNGS,
    EFan.CONCEALED_HAND,
  ],
  [EFan.PURE_TERMINAL_CHOWS]: [
    EFan.FULL_FLUSH,
    EFan.ALL_CHOWS,
    EFan.PURE_DOUBLE_CHOW,
    EFan.TWO_TERMINAL_CHOWS,
    EFan.NO_HONORS,
  ],

  // 48 points
  [EFan.QUADRUPLE_CHOW]: [EFan.PURE_TRIPLE_CHOW, EFan.PURE_DOUBLE_CHOW, EFan.TILE_HOG],
  [EFan.FOUR_PURE_SHIFTED_PUNGS]: [EFan.PURE_SHIFTED_PUNGS, EFan.ALL_PUNGS],

  // 32 points
  [EFan.FOUR_PURE_SHIFTED_CHOWS]: [EFan.PURE_SHIFTED_CHOWS],
  [EFan.THREE_KONGS]: [EFan.TWO_CONCEALED_KONGS, EFan.TWO_MELDED_KONGS, EFan.CONCEALED_KONG, EFan.MELDED_KONG],
  [EFan.ALL_TERMINALS_AND_HONORS]: [EFan.PUNG_OF_TERMINALS_OR_HONORS, EFan.ALL_PUNGS, EFan.OUTSIDE_HAND],

  // 24 points
  [EFan.SEVEN_PAIRS]: [EFan.CONCEALED_HAND, EFan.SINGLE_WAIT],
  [EFan.GREATER_HONORS_AND_KNITTED_TILES]: [EFan.ALL_TYPES, EFan.CONCEALED_HAND],
  [EFan.ALL_EVEN_PUNGS]: [EFan.ALL_PUNGS, EFan.NO_HONORS, EFan.ALL_SIMPLES],
  [EFan.FULL_FLUSH]: [EFan.NO_HONORS],
  [EFan.PURE_TRIPLE_CHOW]: [EFan.PURE_DOUBLE_CHOW],
  [EFan.UPPER_TILES]: [EFan.UPPER_FOUR, EFan.NO_HONORS],
  [EFan.MIDDLE_TILES]: [EFan.ALL_SIMPLES, EFan.NO_HONORS],
  [EFan.LOWER_TILES]: [EFan.LOWER_FOUR, EFan.NO_HONORS],

  // 16 points
  [EFan.PURE_STRAIGHT]: [EFan.SHORT_STRAIGHT, EFan.TWO_TERMINAL_CHOWS],
  [EFan.THREE_SUITED_TERMINAL_CHOWS]: [EFan.TWO_TERMINAL_CHOWS, EFan.ALL_CHOWS, EFan.NO_HONORS, EFan.MIXED_DOUBLE_CHOW],
  [EFan.ALL_FIVES]: [EFan.ALL_SIMPLES, EFan.NO_HONORS],
  [EFan.TRIPLE_PUNG]: [EFan.DOUBLE_PUNG],
  [EFan.THREE_CONCEALED_PUNGS]: [EFan.TWO_CONCEALED_PUNGS],

  // 12 points
  [EFan.LESSER_HONORS_AND_KNITTED_TILES]: [EFan.ALL_TYPES, EFan.CONCEALED_HAND],
  [EFan.UPPER_FOUR]: [EFan.NO_HONORS],
  [EFan.LOWER_FOUR]: [EFan.NO_HONORS],
  [EFan.BIG_THREE_WINDS]: [EFan.PUNG_OF_TERMINALS_OR_HONORS],

  // 8 points
  [EFan.REVERSIBLE_TILES]: [EFan.ONE_VOIDED_SUIT],
  [EFan.MIXED_TRIPLE_CHOW]: [EFan.MIXED_DOUBLE_CHOW],
  [EFan.LAST_TILE_DRAW]: [EFan.SELF_DRAWN],
  [EFan.OUT_WITH_REPLACEMENT_TILE]: [EFan.SELF_DRAWN],
  [EFan.ROBBING_THE_KONG]: [EFan.LAST_TILE],
  [EFan.TWO_CONCEALED_KONGS]: [EFan.TWO_CONCEALED_PUNGS, EFan.CONCEALED_KONG],

  // 6 points
  [EFan.MELDED_HAND]: [EFan.SINGLE_WAIT],
  [EFan.TWO_DRAGON_PUNGS]: [EFan.DRAGON_PUNG, EFan.PUNG_OF_TERMINALS_OR_HONORS],

  // 4 points
  [EFan.FULLY_CONCEALED_HAND]: [EFan.CONCEALED_HAND, EFan.SELF_DRAWN],
  [EFan.TWO_MELDED_KONGS]: [EFan.MELDED_KONG],

  // 2 points
  [EFan.DRAGON_PUNG]: [EFan.PUNG_OF_TERMINALS_OR_HONORS],
  [EFan.PREVALENT_WIND]: [EFan.PUNG_OF_TERMINALS_OR_HONORS],
  [EFan.SEAT_WIND]: [EFan.PUNG_OF_TERMINALS_OR_HONORS],
  [EFan.ALL_CHOWS]: [EFan.NO_HONORS],
  [EFan.ALL_SIMPLES]: [EFan.NO_HONORS],
};
