export enum CardId {
  // Buildings

  // Residential
  NURSING_HOME = 'NURSING_HOME',

  // Transport
  TAXI_STATION = 'TAXI_STATION',

  // State
  PRISON = 'PRISON',

  // Observations
  HIGH_FIVE = 'HIGH_FIVE',
  TWO_TIMES_TWO = 'TWO_TIMES_TWO',
  DOMINATING_KIND = 'DOMINATING_KIND',
  SINGLE_LANDMARK = 'SINGLE_LANDMARK',
  EMERALD_CITY = 'EMERALD_CITY',
  TWO_OF_EVERY_KIND = 'TWO_OF_EVERY_KIND',
  CATEGORICAL_BALANCE = 'CATEGORICAL_BALANCE',
  SMALL_FAMILY = 'SMALL_FAMILY',
  MOBILE_CITY = 'MOBILE_CITY',
  GRANDPAS_FORTUNE = 'GRANDPAS_FORTUNE',

  // Actions
  ACADEMIC_LEAVE = 'ACADEMIC_LEAVE',
  MUTUAL_DISARMAMENT = 'MUTUAL_DISARMAMENT',
  RENOVATION = 'RENOVATION',

  // Abilities
  ALTERNATIVE_ENERGY = 'ALTERNATIVE_ENERGY',
  BIG_HAND = 'BIG_HAND',
}

export enum CardType {
  BUILDING = 'BUILDING',
  OBSERVATION = 'OBSERVATION',
  ACTION = 'ACTION',
  ABILITY = 'ABILITY',
}

export interface BaseCardDef {
  isBonus: boolean;
}
